name: ntf
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.1.2
  - pytorch==1.6.0
  - pip:
    - matplotlib==3.4.2
    - scipy==1.6.3
    - numpy==1.20.3
    - tqdm==4.60.0
    - PyYAML==5.4
    - scikit_learn==0.24.2
    - opennmt-py==2.1.2
    - pandas==1.3.3
    - pytrec_eval==0.5
    - gensim==3.8.3
