## RNN with Attention Configuration

## Where the samples will be written
save_data: ../output/nmt/run/rnn

## Where the vocab(s) will be written
src_vocab: ../output/nmt/run/rnn.vocab.src
tgt_vocab: ../output/nmt/run/rnn.vocab.tgt

# Prevent overwriting existing files in the folder
overwrite: True

# Corpus opts:
data:
    corpus_1:
        path_src: ../output/nmt/src-train.txt
        path_tgt: ../output/nmt/tgt-train.txt
    valid:
        path_src: ../output/nmt/src-val.txt
        path_tgt: ../output/nmt/tgt-val.txt

# Vocabulary files that were just created
src_vocab: ../output/nmt/run/rnn.vocab.src
tgt_vocab: ../output/nmt/run/rnn.vocab.tgt

# Train on a single GPU
world_size: 1
gpu_ranks: [0]

# Where to save the checkpoints
save_model: ../output/nmt/run/rnn_model
save_checkpoint_steps: 500
train_steps: 1000

keep_checkpoint: -1
seed: 0
valid_steps: 1000
report_every: 1000

# Model hyperparameters
word_vec_size: 256
rnn_size: 512
layers: 2

encoder_type: rnn
decoder_type: rnn
rnn_type: LSTM

optim: adam
learning_rate: 0.0005
learning_rate_decay: 0.95
start_decay_steps: 100
decay_steps: 100
batch_size: 16
dropout: 0.4