## Where the samples will be written
save_data: ../output/nmt/run/example
## Where the vocab(s) will be written
src_vocab: ../output/nmt/run/example.vocab.src
tgt_vocab: /run/example.vocab.tgt
# Prevent overwriting existing files in the folder
overwrite: False

# Corpus opts:
data:
    corpus_1:
        path_src: ../output/nmt/src-train.txt
        path_tgt: ../output/nmt/tgt-train.txt
    valid:
        path_src: ../output/nmt/src-val.txt
        path_tgt: ../output/nmt/tgt-val.txt

# Vocabulary files that were just created
src_vocab: ../output/nmt/run/example.vocab.src
tgt_vocab: ../output/nmt/run/example.vocab.tgt

# Train on a single GPU
world_size: 1
gpu_ranks: [0]

# Where to save the checkpoints
save_model: ../output/nmt/run/model
save_checkpoint_steps: 20
train_steps: 100

keep_checkpoint: 10
seed: 0
valid_steps: 10
report_every: 10

encoder_type: rnn
decoder_type: rnn
word_vec_size: 256
rnn_size: 512
layers: 1

optim: adam
learning_rate: 0.001
learning_rate_decay: 0.9
start_decay_steps: 50
decay_steps: 50

batch_size: 32
# dropout: 0.5

# copy_attn: 'true'
# global_attention: mlp
# reuse_copy_attn: 'true'
# bridge: 'true'